version: "3.8"

services:
  db:
    image: mysql
    container_name: testdb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sopes_db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  server:
    image: testapi
    container_name: testserver
    privileged: true
    pid: host
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /proc:/host_proc
    depends_on:
      - db
  client:
    image: testfrontend
    container_name: testclient
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
volumes:
  db-data:
